# Generated by Django 4.2.7 on 2024-01-14 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_task_description_itinerary'),
        ('users', '0005_event'),
    ]

    operations = [
    ]
