# Generated by Django 4.2.7 on 2024-01-14 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_merge_20240114_1841'),
        ('users', '0006_merge_20240114_1956'),
    ]

    operations = [
    ]
